### ISSUE TITLE
Please add PCB and GERBER files for whole cube

### ISSUE THREAD

**Issue by arduino12** [Noteolvides/CubeTouch#24]
**Amazing work!!!**

Can you please add to the repo the PCB and GERBER files of the whole cube (the one showd in the video)?
I only found [individual PCB files](https://github.com/Noteolvides/CubeTouch/tree/main/Hardware) for each cube face:

I will surely contribute some code examples after I build my own soon :)

**Thanks! :)**

**Comment by Noteolvides** [comment]
Hi, all the info is here!
https://github.com/Noteolvides/CubeTouch
This is the main repo also, you will be able to buy it soon if you want to support me!
More info here soon.
https://cubetouch.noteolvid.es/
